config/routes.rb
Rails.application.routes.draw do
  root :to => "home#index"
  get '/dev' => "home#dev"
get '/price' => "home#price"
get '/customers' => "home#customers"
get '/features' => "home#features"

get '/agreement' => "home#agreement"
get '/privacy' => "home#privacy"

  get '/login' => 'users#login'
  get '/register' => 'users#register'
  get '/logout' => 'users#logout'

   get '/@:id' => 'users#show'
   post '/users' => 'users#create'
   post '/session' => 'users#sessionCreate'

  delete '/@:id' => 'users#destory'

  get	'/@:username/apps'=> 'apps#index'
  post	'/@:username/apps' =>	'apps#create'

  get	'/@:username/apps/new' =>	'apps#new'
  get	'/@:username/apps/:id/edit' =>	'apps#edit'
  get	'/@:username/apps_log' =>	'apps#showlog'
  get	'/@:username/feedback' => 'apps#feedback'

  get	'/@:username/apps/:id' =>	'apps#show'

  patch '/@:username/apps/:id' => 'apps#update'
  put	'/@:username/apps/:id' =>	'apps#update'
  delete	'/@:username/apps/:id' =>	'apps#destroy'




  get	'/@:username/apps/:app_id/dataconsole'=> 'dataconsole#index'
  get	'/@:username/apps/:app_id/dataconsole/api'=> 'dataconsole#apiExecute'

  get '/@:username/apps/:app_id/dataconsole/collections'=> 'dataconsole#indexScheme'
  post '/@:username/apps/:app_id/dataconsole/collections/new'=> 'dataconsole#createScheme'

  get	'/@:username/apps/:app_id/dataconsole/collections/:collection'=> 'dataconsole#indexData'
  post	'/@:username/apps/:app_id/dataconsole/collections/:collection'=> 'dataconsole#createData'
  delete '/@:username/apps/:app_id/dataconsole/collections/:collection'=> 'dataconsole#deleteScheme'
  patch '/@:username/apps/:app_id/dataconsole/collections/:collection'=> 'dataconsole#updateScheme'

  get	'/@:username/apps/:app_id/dataconsole/collections/:collection/:objectId'=> 'dataconsole#showObject'

  delete '/@:username/apps/:app_id/dataconsole/collections/:collection/:objectId'=> 'dataconsole#deleteObject'
  patch '/@:username/apps/:app_id/dataconsole/collections/:collection/:objectId'=> 'dataconsole#updateObject'



 end

app/models/user.rb
require 'bcrypt'

class User < ActiveRecord::Base
  has_many :apps
  validates :name, presence: true
  before_save { self.email = email.downcase }
  validates :username, format: { with: /\A[a-zA-Z0-9]+\Z/ }
  validates :contact, :numericality => {:only_integer => true}
  attr_accessor :new_password
  before_save :hash_new_password, :if=>:password_changed?

  def password_changed?
    !@new_password.blank?
  end

  def hash_new_password
    self.password = BCrypt::Password.create(@new_password)
  end

  def self.authenticate(username, password)
    if user = User.find_by(username: username)
      if BCrypt::Password.new(user.password).is_password? password
        return user
      end
    end
    return nil
  end

end

app/controllers/users_controller.rb
class UsersController < ActionController::Base
  before_action :vaildate_session, only: [:login, :register, :sessionCreate, :create]
  before_action :set_user, only: [:edit, :update, :destroy]
  skip_before_action :verify_authenticity_token
  require 'securerandom'

  def login

  end

  def register
  end

  def logout
    session[:user_id] = nil
    redirect_to "/"
   end

  def show
  end

  def sessionCreate
    formData = params[:user]
    if formData[:username] != nil and formData[:password] != nil

      if @user = User.authenticate(formData[:username], formData[:password])
        session[:user_id] = @user.id
        redirect_to "/@#{@user.username}/apps/"
        return
      end
    end
    redirect_to :login, :flash => { message: "Username or Password does not match." }
  end

  def edit

  end

  def create
    @user = User.new(user_params)
    @user.new_password = @user.password

    if User.find_by(username: @user.username) != nil
      redirect_to :register , :flash => { message: "중복된 아이디입니다" }
      return
    end
    if @user.username.size < 4
	redirect_to :register , :flash => { message: "id가 짧습니다." }
	return
    end
    if @user.password.size < 6
	redirect_to :register , :flash => { message: "패스워드가 짧습니다." }
	return
    end
    if @user.name.size < 2
	redirect_to :register , :flash => { message: "이름이 짧습니다." }
	return
    end
    if @user.contact.size != 11
      redirect_to :register , :flash => { message: " 연락처를 알맞게 입력해주세요. -(하이픈)은 포함하지 않습니다." }
      return
    end

    if @user.email.size < 2
      redirect_to :register , :flash => { message: "이메일을 알맞게 입력해주세요." }
      return
    end

    @user.api_key = SecureRandom.uuid
    if @user.save
      session[:user_id] = @user.id
      redirect_to "/@#{@user.username}/apps/"
    	return
    else
    	redirect_to :register , :flash => { message: "양식을 알맞게 채워주세요." }
    	return
    end
  end

  # PATCH/PUT /users/1
   def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
   def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
     end
  end

  private
    def set_user
      #@user = User.find(session[:user_id])
    end

    def vaildate_session
      if session[:user_id]
        @user = User.find_by(id: session[:user_id])

        if @user
          redirect_to "/@#{@user.username}/apps/"
        end
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :email, :password, :contact, :name)

    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/login.html.erb
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js">
<!--<![endif]-->

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>SpaceLab</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    <!-- Favicon -->
    <link rel="shortcut icon" href="assets/img/favicon.ico" type="image/x-icon">
    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="assets/plugins/bootstrap/css/bootstrap.min.css">
    <!-- Fonts from Font Awsome -->
    <link rel="stylesheet" href="assets/css/font-awesome.min.css">
    <!-- CSS Animate -->
    <link rel="stylesheet" href="assets/css/animate.css">
    <!-- Custom styles for this theme -->
    <link rel="stylesheet" href="assets/css/main.css">
    <!-- Fonts -->
    <link href='https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,900,300italic,400italic,600italic,700italic,900italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,700' rel='stylesheet' type='text/css'>
    <!-- Feature detection -->
    <script src="assets/js/modernizr-2.6.2.min.js"></script>
    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="assets/js/html5shiv.js"></script>
    <script src="assets/js/respond.min.js"></script>
    <![endif]-->
</head>

<body class="animated fadeIn">
    <section id="login-container">

        <div class="row">
            <div class="col-md-3" id="login-wrapper">
                <div class="panel panel-primary animated flipInY">
                    <div class="panel-heading">
                        <h3 class="panel-title">
                           Sign In
                        </h3>
                    </div>
                    <div class="panel-body">
                      <% if flash[:message] %>
                         <div class="alert alert-danger alert-dismissable"><button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button><%= flash[:message]%></div>
                      <% end %>
                       <p> Login to access your account.</p>
                      <form accept-charset="UTF-8" action="/session" id="create_session" method="post" class="form-horizontal" role="form">
                            <div class="form-group">
                                <div class="col-md-12">
                                    <input type="text" class="form-control" id="email" name="user[username]" placeholder="Username">
                                    <i class="fa fa-user"></i>
                                </div>
                            </div>
                            <div class="form-group">
                               <div class="col-md-12">
                                    <input type="password" class="form-control" id="password" name="user[password]" placeholder="Password">
                                    <i class="fa fa-lock"></i>
                                    <a href="javascript:void(0)" class="help-block">Forgot Your Password?</a>
                                </div>
                            </div>
                            <div class="form-group">
                               <div class="col-md-12">
                                 <input class="btn btn-primary btn-block" type="submit" value="Sign in">
                                    <hr />
                                    <a href="/register" class="btn btn-default btn-block">Not a member? Sign Up</a>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>

    </section>
    <!--Global JS-->
    <script src="assets/js/jquery-1.10.2.min.js"></script>
    <script src="assets/plugins/bootstrap/js/bootstrap.min.js"></script>
    <script src="assets/plugins/waypoints/waypoints.min.js"></script>
    <script src="assets/plugins/nanoScroller/jquery.nanoscroller.min.js"></script>
    <script src="assets/js/application.js"></script>
</body>

</html>


<!--
<div id="page-wrapper-non-nav" >
    <div id="page-inner-short">

      <div class="row">
        <div class="col-md-6 col-md-offset-3 top1">
          <h1>로그인을 해주세요.</h1>
          <% if flash[:message] %>
          <br>
            <p class="alert alert-danger alert-dismissable"><button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button><%= flash[:message]%></p>
          <% end %>
          <hr/>
<div class="panel panel-primary">
  <div class="panel-heading">
    <h3 class="panel-title">Login</h3>
  </div>
  <div class="panel-body">
    <form accept-charset="UTF-8" action="/session" class="create_session" id="create_session" method="post">

<div class="form-group">
   <input type="text" id="user_username" name="user[username]" class="form-control" placeholder="ID">
</div>
<div class="form-group">
<input type="password" id="user_pw" name="user[password]" class="form-control" placeholder="Password">
</div>

 <a>아이디 찾기</a><span> | </span><a>비밀번호 찾기</a>
 <hr/>
 <div class="pull-right">

        <input class="btn btn-success btn-lg" type="submit" value="Login">
       <a class="btn btn-primary btn-lg" href="/register">Join</a>


  </div>
</form>

  </div>

</div>
</div>
</div>
</div>
</div>
-->

app/views/users/register.html.erb
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js">
<!--<![endif]-->

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>RankaaS - 인디게임 개발자분을 위한 게임 백엔드 서비스</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    <!-- Favicon -->
    <link rel="shortcut icon" href="assets/img/favicon.ico" type="image/x-icon">
    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="assets/plugins/bootstrap/css/bootstrap.min.css">
    <!-- Fonts from Font Awsome -->
    <link rel="stylesheet" href="assets/css/font-awesome.min.css">
    <!-- CSS Animate -->
    <link rel="stylesheet" href="assets/css/animate.css">
    <!-- Custom styles for this theme -->
    <link rel="stylesheet" href="assets/css/main.css">
    <link rel="stylesheet" href="assets/plugins/icheck/css/_all.css">

    <!-- Fonts -->
    <link href='https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,900,300italic,400italic,600italic,700italic,900italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,700' rel='stylesheet' type='text/css'>
    <!-- Feature detection -->
    <script src="/assets/js/modernizr-2.6.2.min.js"></script>

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="assets/js/html5shiv.js"></script>
    <script src="assets/js/respond.min.js"></script>
    <![endif]-->
</head>

<body class="animated fadeIn">
    <section id="login-container">

        <div class="row">
            <div class="col-md-3" id="login-wrapper">
                <div class="panel panel-primary animated flipInY">
                    <div class="panel-heading">
                          <h3 class="panel-title">
                           Sign Up
                        </h3>
                    </div>
                    <div class="panel-body">
                        <p >Already a member? <a href="/login"><strong>Sign In</strong></a></p>
                        <form accept-charset="UTF-8" action="/users" id="create_user" method="post">
                            <div class="form-group">
                                <label >ID</label>
                                <input type="text" name="user[username]" class="form-control" id="username" placeholder="Enter your ID">
                            </div>
                            <div class="form-group">
                                <label>Name</label>
                                <input type="text" name="user[name]" class="form-control" id="name" placeholder="Enter your name">
                            </div>

                             <div class="form-group">
                                <label>Password</label>
                                <input type="password" name="user[password]" id="user_password" class="form-control" id="exampleInputPassword1" placeholder="Password">
                            </div>
                              <div class="form-group">
                                <label>Retype Password</label>
                                <input type="password" name="user[retype_password]" id="retype_password" class="form-control" id="exampleInputPassword1" placeholder="Retype your password">
                            </div>
                            <div class="form-group">
                                <label>Email</label>
                                <input type="email" name="user[email]" class="form-control" placeholder="Enter your email">
                            </div>

                            <div class="form-group">
                               <label>Phone Number</label>
                               <input type="text" name="user[contact]" class="form-control" id="exampleInputPassword1" placeholder="Enter your Phone Number (only number)">
                            </div>
                            <div class="form-group">
                                <input name="user[agree]" type="checkbox">
                                <label><a href="/agreement">약관</a>에 동의합니다.</label>
                            </div>
                            <input type="button" class="btn btn-primary btn-block" id="submit_button" value="Sign Up">

                        </form>

                    </div>
                </div>
            </div>
        </div>

    </section>
    <!--Global JS-->
    <script src="/assets/js/jquery-1.10.2.min.js"></script>
    <script src="/assets/plugins/bootstrap/js/bootstrap.min.js"></script>
    <script src="/assets/plugins/waypoints/waypoints.min.js"></script>
    <script src="/assets/plugins/nanoScroller/jquery.nanoscroller.min.js"></script>
    <script src="/assets/js/application.js"></script>
    <script src="/assets/plugins/validation/js/jquery.validate.min.js"></script>
    <script src="/assets/plugins/icheck/js/icheck.min.js"></script>
    <script>
    jQuery.validator.addMethod("noSpace", function(value, element) {
     return value.indexOf(" ") < 0 && value != "";
   }, "Space are not allowed");


        $(document).ready(function() {
            $('input').iCheck({
                checkboxClass: 'icheckbox_flat-grey',
                radioClass: 'iradio_flat-grey'
            });

            $("#submit_button").click(function(){
              if ($("#create_user").valid())
              $("#create_user").submit();
            });

            $("#create_user").validate({
              rules : {
                "user[email]" : {
                  required : true,
                  email : true
                },
                "user[name]" : {
                  required : true,
                },
              "user[password]" : {
                required : true,
                minlength : 6,
              },
              "user[retype_password]" : {
                required : true,
                minlength : 6,
                equalTo : "#user_password"
              },
              "user[contact]" : {
                required : true,
                number: true,
                minlength : 11,
                maxlength : 11,
              },
              "user[username]" : {
                required : true,
                noSpace : true
              }

            },
            highlight: function(element) {
                        $(element).parent().find("label").removeClass("hide").closest('.form-group').removeClass('has-success').addClass('has-error has-feedback');
               $(element).parent().find("span").remove();
                 },
              success: function(element) {
                element.addClass('valid hide').closest('.form-group').removeClass('has-error').addClass('has-success has-feedback');
                 element.parent().append('<span class="glyphicon glyphicon-ok form-control-feedback"></span>')
                   },


            })

        });
    </script>

</body>

</html>

<!--
  <div id="page-wrapper-non-nav" >
    <div id="page-inner-short">
         <div class="col-md-8 col-md-offset-2">
          <h1>환영합니다</h1>
	<% if flash[:message] %>
<br> <p class="alert alert-danger alert-dismissable"><button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button><%= flash[:message]%></p> <% end %>
          <hr/>
          <div class="panel panel-primary">
            <div class="panel-heading">
              <h3 class="panel-title">Join</h3>
            </div>
            <div class="panel-body">
              <form accept-charset="UTF-8" action="/users" class="create_user" id="create_user" method="post">
              <br>
              <div class="form-group col-md-12">
                <label class="col-sm-2 control-label">ID</label>
                <div class="col-sm-10">
                  <input type="text" class="form-control" name="user[username]" placeholder="아이디는 4자 이상, 공백을 포함할 수 없습니다.">
                </div>
              </div>
                <div class="form-group col-md-12">
                  <label class="col-sm-2 control-label">Password</label>
                  <div class="col-sm-10">
                    <input type="password" class="form-control" name="user[password]" placeholder="패스워드는 6자 이상입니다.">
                  </div>
                </div>
                 <div class="form-group col-md-12">
                  <label class="col-sm-2 control-label">이름</label>
                  <div class="col-sm-10">
                    <input type="text" class="form-control" name="user[name]" placeholder="2글자 이상 입력해주세요.">
                  </div>
                </div>
                <div class="form-group col-md-12">
                <label class="col-sm-2 control-label">Email</label>
                <div class="col-sm-10">
                  <input type="email" class="form-control" name="user[email]" placeholder="Email">
                </div>
              </div>

                <div class="form-group col-md-12">
                  <label class="col-sm-2 control-label">연락처</label>
                  <div class="col-sm-10">
                    <input type="text" class="form-control" name="user[contact]" placeholder="연락처 -(하이픈)은 빼고 입력해주세요.">
                  </div>
                </div>
                <div class="form-group col-md-12">
                  <div class="col-sm-10 col-md-offset-2">
                      <div class="checkbox">
        <label>
          <input name="user[agree]" type="checkbox"> <b><a>약관</a>에 동의합니다.</b></input>
        </label>
      </div>
    </div>
</div>

                <div class="form-group col-md-12">
                  <div class="col-sm-10 col-md-offset-2">
                    <div class="pull-right">
                    <input class="btn btn-success btn-lg" type="submit" value="회원가입">
                   <input class="btn btn-danger btn-lg" type="submit" value="취소">
                 </div>
               </div>
</div>
</form>
              </div>
          </div>
        </div>

    </div>

  </div>

</div>-->